[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anchor_nft_staking = "9QtXBKnLPGkv6EmtF4Pk8p75NSH8wPLXkP1K3Ydshb5k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ronak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
